import datetime

import click

import codemonkey.lib as lib
import codemonkey.pip.dists as dists


@click.command()
@click.version_option()
@click.option("--include-devel/--just-pip-packages", "editables", default=False)
@click.option(
    "-i", "--ignore", multiple=True, help="Don't list these packages", metavar="<package list>"
)
@click.option("-p", "--show", multiple=True, help="list these packages", metavar="<package list>")
def main(editables, ignore, show):
    showset = lib.option_to_set(show)
    ignoreset = lib.option_to_set(ignore)
    keepset = dists.VIRTUALENV_PKGS | dists.COMMON_PKGS | showset

    if editables:
        skipset = ignoreset
        distlist = dists.get_distributions(ignore=skipset)
    else:
        skipset = (dists.PIPTOOLS_PKGS - keepset) | ignoreset
        distlist = dists.get_distributions(ignore=skipset, editable=False)

    print(f"# This file autogenerated by pip-chill")
    print(f'# at {datetime.datetime.now()} with "{lib.cmdline()}"')
    print("#\n")

    for d in distlist:
        print(dists.make_spec(d))


# end
